// +gocover:ignore:file it is a temporary tool only used during the overlay.resource migration
package main

import (
	"fmt"
	"io/fs"
	"path"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/spf13/cobra"
)

func GetCheckCMD() *cobra.Command {
	var ev2ab, aksbuilder string
	cmd := &cobra.Command{
		Use:   "check",
		Short: "check if the ev2ab artifacts are a subset of aksbuilder artifacts for specific ARM template",
		Long:  "check if the ev2ab artifacts are a subset of aksbuilder artifacts for specific ARM template",
		RunE: func(command *cobra.Command, args []string) error {
			var templateName, ev2abFolder, aksbuilderFolder string
			for _, v := range matrix {
				ev2abFolder = path.Join(ev2ab, v.Ev2abTarget)
				aksbuilderFolder = path.Join(aksbuilder, v.AksbuilderEv2Name)
				templateName = v.Name
				if err := runDiff(templateName, ev2abFolder, aksbuilderFolder); err != nil {
					return err
				}
			}
			return nil
		},
	}

	cmd.Flags().StringVar(&ev2ab, "ev2ab", "", "the artifacts generated by ev2ab")
	cmd.Flags().StringVar(&aksbuilder, "aksbuilder", "gb", "the artifacts generated by aksbuilder")
	return cmd
}

func runDiff(templateName, ev2abFolder, aksbuilderFolder string) error {
	var walkErr error

	// build artifact with ev2ab and output to <ev2abFolder>
	// build artifact with aksbuilder and output to <aksbuilderFolder>
	// <ev2Name> is the target ARM template
	// templateName = "flt"
	// ev2abFolder = "/home/zhongz/tmp/drop_ev2_build/overlay.resource.region"
	// aksbuilderFolder = "/home/zhongz/go/src/go.goms.io/aks/rp/out/fleet-regionresources.gotemplate.ev2"

	rolloutSpecFileRe := regexp.MustCompile(`([\w\d]+\.[\w\d]+\.[\w\d]+)\.RolloutSpec\.json`)
	walkErr = filepath.WalkDir(ev2abFolder, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if rolloutSpecFileRe.MatchString(d.Name()) {
			region := rolloutSpecFileRe.ReplaceAllString(d.Name(), "$1")
			if strings.Contains(region, "test") ||
				region == "mc.int.chinanorth2" {
				// skip the test regions and not ready regions
				return nil
			}

			if err := checkParameters(ev2abFolder, aksbuilderFolder, region, templateName); err != nil {
				return fmt.Errorf("checkParameters err in region %s: %s", region, err)
			}

			if err := checkResources(ev2abFolder, aksbuilderFolder, region, templateName); err != nil {
				return fmt.Errorf("checkParameters err in region %s: %s", region, err)
			}

			fmt.Printf("region %s passed\n", region)
		}
		return nil
	})
	if walkErr != nil {
		return fmt.Errorf("WalkDir err: %s", walkErr)
	}

	return nil
}
